version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hue-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hue-network

networks:
  hue-network:
    driver: bridge
